apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mygpt.fullname" . }}-litellm-config
  namespace: {{ .Values.namespace }}
  labels: {{- include "mygpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: litellm
data:
  config.yaml: |
    {{- .Files.Get "files/litellm_config.yaml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mygpt.fullname" . }}-initdb
  namespace: {{ .Values.namespace }}
  labels: {{- include "mygpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
data:
  initdb.sql: |
    {{- .Files.Get "files/initdb.sql" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mygpt.fullname" . }}-searxng
  namespace: {{ .Values.namespace }}
  labels: {{- include "mygpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: searxng
data:
  settings.yml: |
    {{- .Files.Get "files/searxng/settings.yml" | nindent 4 }}
  uwsgi.ini: |
    {{- .Files.Get "files/searxng/uwsgi.ini" | nindent 4 }}
