apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mygpt.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
  labels: {{- include "mygpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "mygpt.selectorLabels" (dict "root" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels: {{- include "mygpt.selectorLabels" (dict "root" . "component" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.images.redis }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: http
          resources:
            {{- toYaml .Values.resources.redis | nindent 12 }}
