apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mygpt.fullname" . }}-openwebui
  namespace: {{ .Values.namespace }}
  labels: {{- include "mygpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: openwebui
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.openwebui }}
