name: Gitleaks CI

on:
  push:
    branches:
      - main  # Change to your target branch
  pull_request:
    branches:
      - main  # Change to your target branch

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'  # Specify the Go version compatible with Gitleaks

      - name: Install Gitleaks
        run: |
          go install github.com/zricethezav/gitleaks/v8@latest

      - name: Run Gitleaks
        id: gitleaks
        run: |
          gitleaks detect --source . --report-format json --report-path gitleaks-report.json || true

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v2
        with:
          name: gitleaks-report
          path: gitleaks-report.json

